-- MySQL Script generated by MySQL Workbench
-- Thu Jan  4 10:43:13 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DisasterDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DisasterDB` ;

-- -----------------------------------------------------
-- Schema DisasterDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DisasterDB` DEFAULT CHARACTER SET cp866 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `DisasterDB` ;

-- -----------------------------------------------------
-- Table `DisasterDB`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DisasterDB`.`user` ;

CREATE TABLE IF NOT EXISTS `DisasterDB`.`user` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `nic` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `account_type` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DisasterDB`.`Report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DisasterDB`.`report` ;

CREATE TABLE IF NOT EXISTS `DisasterDB`.`report` (
  `Reportid` INT NOT NULL AUTO_INCREMENT,
  `date` VARCHAR(255) NULL,
  `Threat_level` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  `longitude` VARCHAR (255) NULL,
  `lat` VARCHAR (255) NULL,
  `photo` VARCHAR(45) NULL,
  `Disaster_Type` VARCHAR(45) NULL,
  `Approved` INT,
  `Title` VARCHAR (255) NULL,
  PRIMARY KEY (`Reportid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DisasterDB`.`Accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DisasterDB`.`accountType` ;

CREATE TABLE IF NOT EXISTS `DisasterDB`.`accountType` (
  `Accid` INT NOT NULL AUTO_INCREMENT,
  `Account_type` VARCHAR(45) NULL,
  `Acc_Description` VARCHAR(45) NULL,
  PRIMARY KEY (`Accid`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
